---
- name: Create application directory
  file:
    path: /opt/portfolio
    state: directory
    mode: "0755"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/portfolio/docker-compose.yml

- name: Pull latest Docker image
  command: docker compose pull
  args:
    chdir: /opt/portfolio

- name: Start containers
  command: docker compose up -d
  args:
    chdir: /opt/portfolio
