- name: Deploy to EC2
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    source: "app/docker-compose.yml"
    target: "/tmp"

- name: Restart Application
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      sudo mkdir -p /opt/portfolio

      sudo mv /tmp/app/docker-compose.yml /opt/portfolio/docker-compose.yml

      cd /opt/portfolio

      docker compose pull

      docker compose up -d --force-recreate

      docker image prune -f
